// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_XYBfJEKKLvH6MeyiUWMcfN4TU30wiE',
    appId: '1:1048638276516:web:07f8238a1979b7aa6c7731',
    messagingSenderId: '1048638276516',
    projectId: 'habitos-saludaables',
    authDomain: 'habitos-saludaables.firebaseapp.com',
    storageBucket: 'habitos-saludaables.firebasestorage.app',
    measurementId: 'G-8BZ94NNW4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-wcKX6cxlUK5UR1umzzeZHlzwM71XY0',
    appId: '1:1048638276516:android:226f962f1e92b66e6c7731',
    messagingSenderId: '1048638276516',
    projectId: 'habitos-saludaables',
    storageBucket: 'habitos-saludaables.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjThC2sdqH1Fgd83DlfdeJyEfYijNJOno',
    appId: '1:1048638276516:ios:1b970503825f5f296c7731',
    messagingSenderId: '1048638276516',
    projectId: 'habitos-saludaables',
    storageBucket: 'habitos-saludaables.firebasestorage.app',
    iosBundleId: 'com.rh-omni777.habitosSaludables',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjThC2sdqH1Fgd83DlfdeJyEfYijNJOno',
    appId: '1:1048638276516:ios:5e3a9b17f6a115aa6c7731',
    messagingSenderId: '1048638276516',
    projectId: 'habitos-saludaables',
    storageBucket: 'habitos-saludaables.firebasestorage.app',
    iosBundleId: 'com.example.habitosSaludables',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR_XYBfJEKKLvH6MeyiUWMcfN4TU30wiE',
    appId: '1:1048638276516:web:90e186914380a9ea6c7731',
    messagingSenderId: '1048638276516',
    projectId: 'habitos-saludaables',
    authDomain: 'habitos-saludaables.firebaseapp.com',
    storageBucket: 'habitos-saludaables.firebasestorage.app',
    measurementId: 'G-VCV98DS8ME',
  );
}
